/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as NewsletterRouteImport } from './routes/newsletter'
import { Route as HireMeRouteImport } from './routes/hire-me'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogsIndexRouteImport } from './routes/blogs/index'
import { Route as WorkRealEstateWhatsappRouteImport } from './routes/work/real-estate-whatsapp'
import { Route as WorkGitReportingRouteImport } from './routes/work/git-reporting'
import { Route as BlogsIdRouteImport } from './routes/blogs/$id'
import { Route as PreviewVideosIndexRouteImport } from './routes/preview/videos/index'
import { Route as PreviewProjectsIndexRouteImport } from './routes/preview/projects/index'
import { Route as PreviewHomeVideosIndexRouteImport } from './routes/preview/home-videos/index'
import { Route as PreviewVideosPairedRouteImport } from './routes/preview/videos/paired'
import { Route as PreviewVideosLogRouteImport } from './routes/preview/videos/log'
import { Route as PreviewVideosLibraryRouteImport } from './routes/preview/videos/library'
import { Route as PreviewProjectsShowcaseRouteImport } from './routes/preview/projects/showcase'
import { Route as PreviewProjectsLogbookDetailRouteImport } from './routes/preview/projects/logbook-detail'
import { Route as PreviewProjectsLogbookRouteImport } from './routes/preview/projects/logbook'
import { Route as PreviewProjectsCaseStudyRouteImport } from './routes/preview/projects/case-study'
import { Route as PreviewHomeVideosHireMeSplitRouteImport } from './routes/preview/home-videos/hire-me-split'
import { Route as PreviewHomeVideosHireMeRouteImport } from './routes/preview/home-videos/hire-me'
import { Route as PreviewHomeVideosBeforeLinksRouteImport } from './routes/preview/home-videos/before-links'
import { Route as PreviewHomeVideosAfterValuesRouteImport } from './routes/preview/home-videos/after-values'
import { Route as PreviewHomeVideosAfterHeroRouteImport } from './routes/preview/home-videos/after-hero'
import { Route as ApiRpcSplatRouteImport } from './routes/api/rpc/$'

const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsletterRoute = NewsletterRouteImport.update({
  id: '/newsletter',
  path: '/newsletter',
  getParentRoute: () => rootRouteImport,
} as any)
const HireMeRoute = HireMeRouteImport.update({
  id: '/hire-me',
  path: '/hire-me',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogsIndexRoute = BlogsIndexRouteImport.update({
  id: '/blogs/',
  path: '/blogs/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkRealEstateWhatsappRoute = WorkRealEstateWhatsappRouteImport.update({
  id: '/work/real-estate-whatsapp',
  path: '/work/real-estate-whatsapp',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkGitReportingRoute = WorkGitReportingRouteImport.update({
  id: '/work/git-reporting',
  path: '/work/git-reporting',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogsIdRoute = BlogsIdRouteImport.update({
  id: '/blogs/$id',
  path: '/blogs/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PreviewVideosIndexRoute = PreviewVideosIndexRouteImport.update({
  id: '/preview/videos/',
  path: '/preview/videos/',
  getParentRoute: () => rootRouteImport,
} as any)
const PreviewProjectsIndexRoute = PreviewProjectsIndexRouteImport.update({
  id: '/preview/projects/',
  path: '/preview/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const PreviewHomeVideosIndexRoute = PreviewHomeVideosIndexRouteImport.update({
  id: '/preview/home-videos/',
  path: '/preview/home-videos/',
  getParentRoute: () => rootRouteImport,
} as any)
const PreviewVideosPairedRoute = PreviewVideosPairedRouteImport.update({
  id: '/preview/videos/paired',
  path: '/preview/videos/paired',
  getParentRoute: () => rootRouteImport,
} as any)
const PreviewVideosLogRoute = PreviewVideosLogRouteImport.update({
  id: '/preview/videos/log',
  path: '/preview/videos/log',
  getParentRoute: () => rootRouteImport,
} as any)
const PreviewVideosLibraryRoute = PreviewVideosLibraryRouteImport.update({
  id: '/preview/videos/library',
  path: '/preview/videos/library',
  getParentRoute: () => rootRouteImport,
} as any)
const PreviewProjectsShowcaseRoute = PreviewProjectsShowcaseRouteImport.update({
  id: '/preview/projects/showcase',
  path: '/preview/projects/showcase',
  getParentRoute: () => rootRouteImport,
} as any)
const PreviewProjectsLogbookDetailRoute =
  PreviewProjectsLogbookDetailRouteImport.update({
    id: '/preview/projects/logbook-detail',
    path: '/preview/projects/logbook-detail',
    getParentRoute: () => rootRouteImport,
  } as any)
const PreviewProjectsLogbookRoute = PreviewProjectsLogbookRouteImport.update({
  id: '/preview/projects/logbook',
  path: '/preview/projects/logbook',
  getParentRoute: () => rootRouteImport,
} as any)
const PreviewProjectsCaseStudyRoute =
  PreviewProjectsCaseStudyRouteImport.update({
    id: '/preview/projects/case-study',
    path: '/preview/projects/case-study',
    getParentRoute: () => rootRouteImport,
  } as any)
const PreviewHomeVideosHireMeSplitRoute =
  PreviewHomeVideosHireMeSplitRouteImport.update({
    id: '/preview/home-videos/hire-me-split',
    path: '/preview/home-videos/hire-me-split',
    getParentRoute: () => rootRouteImport,
  } as any)
const PreviewHomeVideosHireMeRoute = PreviewHomeVideosHireMeRouteImport.update({
  id: '/preview/home-videos/hire-me',
  path: '/preview/home-videos/hire-me',
  getParentRoute: () => rootRouteImport,
} as any)
const PreviewHomeVideosBeforeLinksRoute =
  PreviewHomeVideosBeforeLinksRouteImport.update({
    id: '/preview/home-videos/before-links',
    path: '/preview/home-videos/before-links',
    getParentRoute: () => rootRouteImport,
  } as any)
const PreviewHomeVideosAfterValuesRoute =
  PreviewHomeVideosAfterValuesRouteImport.update({
    id: '/preview/home-videos/after-values',
    path: '/preview/home-videos/after-values',
    getParentRoute: () => rootRouteImport,
  } as any)
const PreviewHomeVideosAfterHeroRoute =
  PreviewHomeVideosAfterHeroRouteImport.update({
    id: '/preview/home-videos/after-hero',
    path: '/preview/home-videos/after-hero',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiRpcSplatRoute = ApiRpcSplatRouteImport.update({
  id: '/api/rpc/$',
  path: '/api/rpc/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/hire-me': typeof HireMeRoute
  '/newsletter': typeof NewsletterRoute
  '/projects': typeof ProjectsRoute
  '/blogs/$id': typeof BlogsIdRoute
  '/work/git-reporting': typeof WorkGitReportingRoute
  '/work/real-estate-whatsapp': typeof WorkRealEstateWhatsappRoute
  '/blogs/': typeof BlogsIndexRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/preview/home-videos/after-hero': typeof PreviewHomeVideosAfterHeroRoute
  '/preview/home-videos/after-values': typeof PreviewHomeVideosAfterValuesRoute
  '/preview/home-videos/before-links': typeof PreviewHomeVideosBeforeLinksRoute
  '/preview/home-videos/hire-me': typeof PreviewHomeVideosHireMeRoute
  '/preview/home-videos/hire-me-split': typeof PreviewHomeVideosHireMeSplitRoute
  '/preview/projects/case-study': typeof PreviewProjectsCaseStudyRoute
  '/preview/projects/logbook': typeof PreviewProjectsLogbookRoute
  '/preview/projects/logbook-detail': typeof PreviewProjectsLogbookDetailRoute
  '/preview/projects/showcase': typeof PreviewProjectsShowcaseRoute
  '/preview/videos/library': typeof PreviewVideosLibraryRoute
  '/preview/videos/log': typeof PreviewVideosLogRoute
  '/preview/videos/paired': typeof PreviewVideosPairedRoute
  '/preview/home-videos/': typeof PreviewHomeVideosIndexRoute
  '/preview/projects/': typeof PreviewProjectsIndexRoute
  '/preview/videos/': typeof PreviewVideosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/hire-me': typeof HireMeRoute
  '/newsletter': typeof NewsletterRoute
  '/projects': typeof ProjectsRoute
  '/blogs/$id': typeof BlogsIdRoute
  '/work/git-reporting': typeof WorkGitReportingRoute
  '/work/real-estate-whatsapp': typeof WorkRealEstateWhatsappRoute
  '/blogs': typeof BlogsIndexRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/preview/home-videos/after-hero': typeof PreviewHomeVideosAfterHeroRoute
  '/preview/home-videos/after-values': typeof PreviewHomeVideosAfterValuesRoute
  '/preview/home-videos/before-links': typeof PreviewHomeVideosBeforeLinksRoute
  '/preview/home-videos/hire-me': typeof PreviewHomeVideosHireMeRoute
  '/preview/home-videos/hire-me-split': typeof PreviewHomeVideosHireMeSplitRoute
  '/preview/projects/case-study': typeof PreviewProjectsCaseStudyRoute
  '/preview/projects/logbook': typeof PreviewProjectsLogbookRoute
  '/preview/projects/logbook-detail': typeof PreviewProjectsLogbookDetailRoute
  '/preview/projects/showcase': typeof PreviewProjectsShowcaseRoute
  '/preview/videos/library': typeof PreviewVideosLibraryRoute
  '/preview/videos/log': typeof PreviewVideosLogRoute
  '/preview/videos/paired': typeof PreviewVideosPairedRoute
  '/preview/home-videos': typeof PreviewHomeVideosIndexRoute
  '/preview/projects': typeof PreviewProjectsIndexRoute
  '/preview/videos': typeof PreviewVideosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/hire-me': typeof HireMeRoute
  '/newsletter': typeof NewsletterRoute
  '/projects': typeof ProjectsRoute
  '/blogs/$id': typeof BlogsIdRoute
  '/work/git-reporting': typeof WorkGitReportingRoute
  '/work/real-estate-whatsapp': typeof WorkRealEstateWhatsappRoute
  '/blogs/': typeof BlogsIndexRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/preview/home-videos/after-hero': typeof PreviewHomeVideosAfterHeroRoute
  '/preview/home-videos/after-values': typeof PreviewHomeVideosAfterValuesRoute
  '/preview/home-videos/before-links': typeof PreviewHomeVideosBeforeLinksRoute
  '/preview/home-videos/hire-me': typeof PreviewHomeVideosHireMeRoute
  '/preview/home-videos/hire-me-split': typeof PreviewHomeVideosHireMeSplitRoute
  '/preview/projects/case-study': typeof PreviewProjectsCaseStudyRoute
  '/preview/projects/logbook': typeof PreviewProjectsLogbookRoute
  '/preview/projects/logbook-detail': typeof PreviewProjectsLogbookDetailRoute
  '/preview/projects/showcase': typeof PreviewProjectsShowcaseRoute
  '/preview/videos/library': typeof PreviewVideosLibraryRoute
  '/preview/videos/log': typeof PreviewVideosLogRoute
  '/preview/videos/paired': typeof PreviewVideosPairedRoute
  '/preview/home-videos/': typeof PreviewHomeVideosIndexRoute
  '/preview/projects/': typeof PreviewProjectsIndexRoute
  '/preview/videos/': typeof PreviewVideosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/hire-me'
    | '/newsletter'
    | '/projects'
    | '/blogs/$id'
    | '/work/git-reporting'
    | '/work/real-estate-whatsapp'
    | '/blogs/'
    | '/api/rpc/$'
    | '/preview/home-videos/after-hero'
    | '/preview/home-videos/after-values'
    | '/preview/home-videos/before-links'
    | '/preview/home-videos/hire-me'
    | '/preview/home-videos/hire-me-split'
    | '/preview/projects/case-study'
    | '/preview/projects/logbook'
    | '/preview/projects/logbook-detail'
    | '/preview/projects/showcase'
    | '/preview/videos/library'
    | '/preview/videos/log'
    | '/preview/videos/paired'
    | '/preview/home-videos/'
    | '/preview/projects/'
    | '/preview/videos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/hire-me'
    | '/newsletter'
    | '/projects'
    | '/blogs/$id'
    | '/work/git-reporting'
    | '/work/real-estate-whatsapp'
    | '/blogs'
    | '/api/rpc/$'
    | '/preview/home-videos/after-hero'
    | '/preview/home-videos/after-values'
    | '/preview/home-videos/before-links'
    | '/preview/home-videos/hire-me'
    | '/preview/home-videos/hire-me-split'
    | '/preview/projects/case-study'
    | '/preview/projects/logbook'
    | '/preview/projects/logbook-detail'
    | '/preview/projects/showcase'
    | '/preview/videos/library'
    | '/preview/videos/log'
    | '/preview/videos/paired'
    | '/preview/home-videos'
    | '/preview/projects'
    | '/preview/videos'
  id:
    | '__root__'
    | '/'
    | '/hire-me'
    | '/newsletter'
    | '/projects'
    | '/blogs/$id'
    | '/work/git-reporting'
    | '/work/real-estate-whatsapp'
    | '/blogs/'
    | '/api/rpc/$'
    | '/preview/home-videos/after-hero'
    | '/preview/home-videos/after-values'
    | '/preview/home-videos/before-links'
    | '/preview/home-videos/hire-me'
    | '/preview/home-videos/hire-me-split'
    | '/preview/projects/case-study'
    | '/preview/projects/logbook'
    | '/preview/projects/logbook-detail'
    | '/preview/projects/showcase'
    | '/preview/videos/library'
    | '/preview/videos/log'
    | '/preview/videos/paired'
    | '/preview/home-videos/'
    | '/preview/projects/'
    | '/preview/videos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HireMeRoute: typeof HireMeRoute
  NewsletterRoute: typeof NewsletterRoute
  ProjectsRoute: typeof ProjectsRoute
  BlogsIdRoute: typeof BlogsIdRoute
  WorkGitReportingRoute: typeof WorkGitReportingRoute
  WorkRealEstateWhatsappRoute: typeof WorkRealEstateWhatsappRoute
  BlogsIndexRoute: typeof BlogsIndexRoute
  ApiRpcSplatRoute: typeof ApiRpcSplatRoute
  PreviewHomeVideosAfterHeroRoute: typeof PreviewHomeVideosAfterHeroRoute
  PreviewHomeVideosAfterValuesRoute: typeof PreviewHomeVideosAfterValuesRoute
  PreviewHomeVideosBeforeLinksRoute: typeof PreviewHomeVideosBeforeLinksRoute
  PreviewHomeVideosHireMeRoute: typeof PreviewHomeVideosHireMeRoute
  PreviewHomeVideosHireMeSplitRoute: typeof PreviewHomeVideosHireMeSplitRoute
  PreviewProjectsCaseStudyRoute: typeof PreviewProjectsCaseStudyRoute
  PreviewProjectsLogbookRoute: typeof PreviewProjectsLogbookRoute
  PreviewProjectsLogbookDetailRoute: typeof PreviewProjectsLogbookDetailRoute
  PreviewProjectsShowcaseRoute: typeof PreviewProjectsShowcaseRoute
  PreviewVideosLibraryRoute: typeof PreviewVideosLibraryRoute
  PreviewVideosLogRoute: typeof PreviewVideosLogRoute
  PreviewVideosPairedRoute: typeof PreviewVideosPairedRoute
  PreviewHomeVideosIndexRoute: typeof PreviewHomeVideosIndexRoute
  PreviewProjectsIndexRoute: typeof PreviewProjectsIndexRoute
  PreviewVideosIndexRoute: typeof PreviewVideosIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/newsletter': {
      id: '/newsletter'
      path: '/newsletter'
      fullPath: '/newsletter'
      preLoaderRoute: typeof NewsletterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hire-me': {
      id: '/hire-me'
      path: '/hire-me'
      fullPath: '/hire-me'
      preLoaderRoute: typeof HireMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogs/': {
      id: '/blogs/'
      path: '/blogs'
      fullPath: '/blogs/'
      preLoaderRoute: typeof BlogsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work/real-estate-whatsapp': {
      id: '/work/real-estate-whatsapp'
      path: '/work/real-estate-whatsapp'
      fullPath: '/work/real-estate-whatsapp'
      preLoaderRoute: typeof WorkRealEstateWhatsappRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work/git-reporting': {
      id: '/work/git-reporting'
      path: '/work/git-reporting'
      fullPath: '/work/git-reporting'
      preLoaderRoute: typeof WorkGitReportingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogs/$id': {
      id: '/blogs/$id'
      path: '/blogs/$id'
      fullPath: '/blogs/$id'
      preLoaderRoute: typeof BlogsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preview/videos/': {
      id: '/preview/videos/'
      path: '/preview/videos'
      fullPath: '/preview/videos/'
      preLoaderRoute: typeof PreviewVideosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preview/projects/': {
      id: '/preview/projects/'
      path: '/preview/projects'
      fullPath: '/preview/projects/'
      preLoaderRoute: typeof PreviewProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preview/home-videos/': {
      id: '/preview/home-videos/'
      path: '/preview/home-videos'
      fullPath: '/preview/home-videos/'
      preLoaderRoute: typeof PreviewHomeVideosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preview/videos/paired': {
      id: '/preview/videos/paired'
      path: '/preview/videos/paired'
      fullPath: '/preview/videos/paired'
      preLoaderRoute: typeof PreviewVideosPairedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preview/videos/log': {
      id: '/preview/videos/log'
      path: '/preview/videos/log'
      fullPath: '/preview/videos/log'
      preLoaderRoute: typeof PreviewVideosLogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preview/videos/library': {
      id: '/preview/videos/library'
      path: '/preview/videos/library'
      fullPath: '/preview/videos/library'
      preLoaderRoute: typeof PreviewVideosLibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preview/projects/showcase': {
      id: '/preview/projects/showcase'
      path: '/preview/projects/showcase'
      fullPath: '/preview/projects/showcase'
      preLoaderRoute: typeof PreviewProjectsShowcaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preview/projects/logbook-detail': {
      id: '/preview/projects/logbook-detail'
      path: '/preview/projects/logbook-detail'
      fullPath: '/preview/projects/logbook-detail'
      preLoaderRoute: typeof PreviewProjectsLogbookDetailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preview/projects/logbook': {
      id: '/preview/projects/logbook'
      path: '/preview/projects/logbook'
      fullPath: '/preview/projects/logbook'
      preLoaderRoute: typeof PreviewProjectsLogbookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preview/projects/case-study': {
      id: '/preview/projects/case-study'
      path: '/preview/projects/case-study'
      fullPath: '/preview/projects/case-study'
      preLoaderRoute: typeof PreviewProjectsCaseStudyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preview/home-videos/hire-me-split': {
      id: '/preview/home-videos/hire-me-split'
      path: '/preview/home-videos/hire-me-split'
      fullPath: '/preview/home-videos/hire-me-split'
      preLoaderRoute: typeof PreviewHomeVideosHireMeSplitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preview/home-videos/hire-me': {
      id: '/preview/home-videos/hire-me'
      path: '/preview/home-videos/hire-me'
      fullPath: '/preview/home-videos/hire-me'
      preLoaderRoute: typeof PreviewHomeVideosHireMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preview/home-videos/before-links': {
      id: '/preview/home-videos/before-links'
      path: '/preview/home-videos/before-links'
      fullPath: '/preview/home-videos/before-links'
      preLoaderRoute: typeof PreviewHomeVideosBeforeLinksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preview/home-videos/after-values': {
      id: '/preview/home-videos/after-values'
      path: '/preview/home-videos/after-values'
      fullPath: '/preview/home-videos/after-values'
      preLoaderRoute: typeof PreviewHomeVideosAfterValuesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preview/home-videos/after-hero': {
      id: '/preview/home-videos/after-hero'
      path: '/preview/home-videos/after-hero'
      fullPath: '/preview/home-videos/after-hero'
      preLoaderRoute: typeof PreviewHomeVideosAfterHeroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rpc/$': {
      id: '/api/rpc/$'
      path: '/api/rpc/$'
      fullPath: '/api/rpc/$'
      preLoaderRoute: typeof ApiRpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HireMeRoute: HireMeRoute,
  NewsletterRoute: NewsletterRoute,
  ProjectsRoute: ProjectsRoute,
  BlogsIdRoute: BlogsIdRoute,
  WorkGitReportingRoute: WorkGitReportingRoute,
  WorkRealEstateWhatsappRoute: WorkRealEstateWhatsappRoute,
  BlogsIndexRoute: BlogsIndexRoute,
  ApiRpcSplatRoute: ApiRpcSplatRoute,
  PreviewHomeVideosAfterHeroRoute: PreviewHomeVideosAfterHeroRoute,
  PreviewHomeVideosAfterValuesRoute: PreviewHomeVideosAfterValuesRoute,
  PreviewHomeVideosBeforeLinksRoute: PreviewHomeVideosBeforeLinksRoute,
  PreviewHomeVideosHireMeRoute: PreviewHomeVideosHireMeRoute,
  PreviewHomeVideosHireMeSplitRoute: PreviewHomeVideosHireMeSplitRoute,
  PreviewProjectsCaseStudyRoute: PreviewProjectsCaseStudyRoute,
  PreviewProjectsLogbookRoute: PreviewProjectsLogbookRoute,
  PreviewProjectsLogbookDetailRoute: PreviewProjectsLogbookDetailRoute,
  PreviewProjectsShowcaseRoute: PreviewProjectsShowcaseRoute,
  PreviewVideosLibraryRoute: PreviewVideosLibraryRoute,
  PreviewVideosLogRoute: PreviewVideosLogRoute,
  PreviewVideosPairedRoute: PreviewVideosPairedRoute,
  PreviewHomeVideosIndexRoute: PreviewHomeVideosIndexRoute,
  PreviewProjectsIndexRoute: PreviewProjectsIndexRoute,
  PreviewVideosIndexRoute: PreviewVideosIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
