/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HireMeRouteImport } from './routes/hire-me'
import { Route as NewsletterRouteImport } from './routes/newsletter'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as BlogsIndexRouteImport } from './routes/blogs/index'
import { Route as BlogsIdRouteImport } from './routes/blogs/$id'
import { Route as WorkGitReportingRouteImport } from './routes/work/git-reporting'
import { Route as WorkRealEstateWhatsappRouteImport } from './routes/work/real-estate-whatsapp'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HireMeRoute = HireMeRouteImport.update({
  id: '/hire-me',
  path: '/hire-me',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsletterRoute = NewsletterRouteImport.update({
  id: '/newsletter',
  path: '/newsletter',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogsIndexRoute = BlogsIndexRouteImport.update({
  id: '/blogs/',
  path: '/blogs/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogsIdRoute = BlogsIdRouteImport.update({
  id: '/blogs/$id',
  path: '/blogs/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkGitReportingRoute = WorkGitReportingRouteImport.update({
  id: '/work/git-reporting',
  path: '/work/git-reporting',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkRealEstateWhatsappRoute = WorkRealEstateWhatsappRouteImport.update({
  id: '/work/real-estate-whatsapp',
  path: '/work/real-estate-whatsapp',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/hire-me': typeof HireMeRoute
  '/newsletter': typeof NewsletterRoute
  '/projects': typeof ProjectsRoute
  '/blogs/$id': typeof BlogsIdRoute
  '/work/git-reporting': typeof WorkGitReportingRoute
  '/work/real-estate-whatsapp': typeof WorkRealEstateWhatsappRoute
  '/blogs/': typeof BlogsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/hire-me': typeof HireMeRoute
  '/newsletter': typeof NewsletterRoute
  '/projects': typeof ProjectsRoute
  '/blogs/$id': typeof BlogsIdRoute
  '/work/git-reporting': typeof WorkGitReportingRoute
  '/work/real-estate-whatsapp': typeof WorkRealEstateWhatsappRoute
  '/blogs': typeof BlogsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/hire-me': typeof HireMeRoute
  '/newsletter': typeof NewsletterRoute
  '/projects': typeof ProjectsRoute
  '/blogs/$id': typeof BlogsIdRoute
  '/work/git-reporting': typeof WorkGitReportingRoute
  '/work/real-estate-whatsapp': typeof WorkRealEstateWhatsappRoute
  '/blogs/': typeof BlogsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/hire-me'
    | '/newsletter'
    | '/projects'
    | '/blogs/$id'
    | '/work/git-reporting'
    | '/work/real-estate-whatsapp'
    | '/blogs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/hire-me'
    | '/newsletter'
    | '/projects'
    | '/blogs/$id'
    | '/work/git-reporting'
    | '/work/real-estate-whatsapp'
    | '/blogs'
  id:
    | '__root__'
    | '/'
    | '/hire-me'
    | '/newsletter'
    | '/projects'
    | '/blogs/$id'
    | '/work/git-reporting'
    | '/work/real-estate-whatsapp'
    | '/blogs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HireMeRoute: typeof HireMeRoute
  NewsletterRoute: typeof NewsletterRoute
  ProjectsRoute: typeof ProjectsRoute
  BlogsIdRoute: typeof BlogsIdRoute
  WorkGitReportingRoute: typeof WorkGitReportingRoute
  WorkRealEstateWhatsappRoute: typeof WorkRealEstateWhatsappRoute
  BlogsIndexRoute: typeof BlogsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hire-me': {
      id: '/hire-me'
      path: '/hire-me'
      fullPath: '/hire-me'
      preLoaderRoute: typeof HireMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/newsletter': {
      id: '/newsletter'
      path: '/newsletter'
      fullPath: '/newsletter'
      preLoaderRoute: typeof NewsletterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogs/': {
      id: '/blogs/'
      path: '/blogs'
      fullPath: '/blogs/'
      preLoaderRoute: typeof BlogsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogs/$id': {
      id: '/blogs/$id'
      path: '/blogs/$id'
      fullPath: '/blogs/$id'
      preLoaderRoute: typeof BlogsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work/git-reporting': {
      id: '/work/git-reporting'
      path: '/work/git-reporting'
      fullPath: '/work/git-reporting'
      preLoaderRoute: typeof WorkGitReportingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work/real-estate-whatsapp': {
      id: '/work/real-estate-whatsapp'
      path: '/work/real-estate-whatsapp'
      fullPath: '/work/real-estate-whatsapp'
      preLoaderRoute: typeof WorkRealEstateWhatsappRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HireMeRoute: HireMeRoute,
  NewsletterRoute: NewsletterRoute,
  ProjectsRoute: ProjectsRoute,
  BlogsIdRoute: BlogsIdRoute,
  WorkGitReportingRoute: WorkGitReportingRoute,
  WorkRealEstateWhatsappRoute: WorkRealEstateWhatsappRoute,
  BlogsIndexRoute: BlogsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
